"""
Worker class for processing files in a separate thread.
"""

import errno
import glob
import json
import os
import shutil
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np
import pandas as pd
from PIL import ExifTags, Image
from qtpy.QtCore import QObject, Signal

from .._edition import update_rings_geometries
from .._settings._settings_manager import SettingsManager
from .._utils._ringtraces_utils import (
    get_instance_labels_linear,
    ring_labels_from_roxas,
)
from .._utils._scl_utils import read_scl
from .._utils._segmentation_postprocess import (
    remove_border_touching_components,
)
from .._writer import write_single_layer


class Worker(QObject):
    """
    Worker for processing files in a separate thread.

    This worker handles finding images, renaming them, extracting metadata,
    and managing the processing flow.
    """

    # Signal definitions
    finished = Signal()  # Emitted when processing is complete
    progress = Signal(int, int)  # current, total - for progress reporting
    metadata_request = Signal(str)  # filename - requests metadata for a file
    abort_signal = Signal()  # Signals to abort processing

    def __init__(
        self,
        project_directory: str,
        scan_content_extension: str,
        metadata_file_extension: str,
        image_file_extensions: List[str],
        selected_files: Optional[List[str]] = None,
        process_processed: bool = False,
        overwrite_files: bool = True,
    ):
        """Initialize the worker with necessary parameters."""
        super().__init__()

        # Directories and file settings
        self.project_directory = project_directory
        self.scan_content_extension = scan_content_extension
        self.metadata_file_extension = metadata_file_extension
        self.image_file_extensions = image_file_extensions
        self.selected_files = selected_files
        self.process_processed = process_processed
        self.overwrite_files = overwrite_files

        # Processing state
        self.should_stop = False
        self.current_file_index = 0
        self.all_files = []
        self.default_metadata = None
        self.default_loading_params = None
        self.apply_to_all = False
        self._current_img_metadata = None  # Temporary cache for image metadata
        self._current_img_loading_params = (
            None  # Temporary cache for loading parameters
        )

        settings = SettingsManager()
        self.cells_content_ext = settings.get(
            "file_extensions.cells_file_extension"
        )[0]
        self.cells_ext = settings.get("file_extensions.cells_file_extension")[
            1
        ]
        self.rings_content_ext = settings.get(
            "file_extensions.rings_file_extension"
        )[0]
        self.rings_ext = settings.get("file_extensions.rings_file_extension")[
            1
        ]

    def _safe_rename_or_copy_delete(self, src: Path, dst: Path) -> Path:
        """
        Rename/move a file without leaving duplicates.
        Uses atomic replace when possible; falls back to copy+delete on cross-device moves.
        """
        src = Path(src)
        dst = Path(dst)

        if not src.exists():
            raise FileNotFoundError(f"Source does not exist: {src}")

        dst.parent.mkdir(parents=True, exist_ok=True)

        # If destination exists, remove it to allow replace semantics
        if dst.exists():
            dst.unlink()

        # Handle case-only rename on case-insensitive filesystems (Windows/macOS default)
        try:
            if (
                src.resolve().as_posix().lower()
                == dst.resolve().as_posix().lower()
                and src.name != dst.name
            ):
                tmp = dst.with_name(dst.name + ".__tmp__")
                os.replace(src, tmp)
                os.replace(tmp, dst)
                return dst
        except OSError:
            # If resolve fails, ignore and proceed with normal path
            pass

        try:
            os.replace(src, dst)  # atomic on same filesystem
            return dst
        except OSError as e:
            if e.errno != errno.EXDEV:
                raise
            # Cross-device rename not possible: copy+delete (still no duplicates at end)
            shutil.copy2(src, dst)
            src.unlink()
            return dst

    def load_cells_from_roxas_scl(self, file_path: str, metadata: Dict = None):
        """
        Load cells from a .scl file generated by ROXAS.

        Args:
            file_path: Path to the image file
        """
        print(f"Attempting to load cells from ROXAS SCL for {file_path}")
        try:

            if os.path.exists(
                scl_file_name := file_path.replace(
                    Path(file_path).suffix, "_Vessels.scl"
                )
            ):
                loaded_cells = read_scl(scl_file_name)
                cells_binary = (loaded_cells > 0).astype("uint8")
                cells_binary = remove_border_touching_components(cells_binary)
                cells_data = (cells_binary * 255).astype("uint8")
                cells_layer_name = (
                    f"{metadata['sample_name']}{self.cells_content_ext}"
                )
                cells_add_kwargs = {
                    "name": cells_layer_name,
                    "features": pd.DataFrame(),
                    "metadata": {
                        **metadata,
                        "cells_segmentation_model": "ROXAS SCL",
                        "cells_segmentation_datetime": datetime.now().isoformat(),
                    },
                }

                cell_path = (
                    Path(file_path).parent
                    / f"{Path(file_path).stem}{self.cells_content_ext}{self.cells_ext}"
                )
                write_single_layer(
                    path=cell_path, data=cells_data, meta=cells_add_kwargs
                )
                print(
                    f"Successfully loaded cells from ROXAS SCL for {file_path}"
                )
            else:
                raise FileNotFoundError(
                    f"SCL file not found for {file_path}: expected at {scl_file_name}"
                )
        except FileNotFoundError as e:
            print(f"Error loading cells from {file_path}: {e}")
            print("Continue without loading cells for this file.")
            return

    def load_rings_from_roxas_ringtraces(
        self, file_path: str, metadata: Dict = None
    ):
        """
        Load rings from a .ringtraces file generated by ROXAS.

        Args:
            file_path: Path to the image file
        """
        print(
            f"Attempting to load rings from ROXAS RingTraces for {file_path}"
        )
        try:
            rings_boundaries = ring_labels_from_roxas(
                file_path,
                image_shape=metadata["scan_size"][::-1],
                return_img_coordinates=True,
            )
            rings_labels = get_instance_labels_linear(
                rings_boundaries,
                image_shape=metadata["scan_size"][::-1],
                draw_lines=False,
            )
            boundary_data = []
            for boundary in rings_boundaries:
                coords = np.flip(
                    boundary.T, axis=1
                )  # flip x and y to get (row, col) format
                boundary_data.append({"RBXY": coords})

            boundaries_df = pd.DataFrame(boundary_data)

            rings_layer_name = (
                f"{metadata['sample_name']}{self.rings_content_ext}"
            )
            rings_data = rings_labels.astype("int32")

            # Get ring years from the ROXAS output file and determine the last complete year based on the maximum year found in the file.
            last_year = (
                max(
                    pd.read_csv(
                        file_path.replace(
                            Path(file_path).suffix, "_Output_Rings.txt"
                        ),
                        sep="\t",
                    )["YEAR"]
                )
                + 1
            )
            # add 1 since roxas does not count partial year at the end

            new_rings_table, _rings_raster_tmp, _cmap_tmp = (
                update_rings_geometries(
                    rings_table=boundaries_df,
                    last_year=int(last_year),
                    image_shape=rings_labels.shape,
                )
            )
            rings_add_kwargs = {
                "name": rings_layer_name,
                # "scale": metadata["Scale"],
                "features": new_rings_table,
                "metadata": {
                    **metadata,
                    "rings_outmost_complete_year": int(last_year),
                    "rings_segmentation_model": "ROXAS RingTraces",
                    "rings_segmentation_datetime": datetime.now().isoformat(),
                },
            }
            ring_path = (
                Path(file_path).parent
                / f"{Path(file_path).stem}{self.rings_content_ext}{self.rings_ext}"
            )
            write_single_layer(
                path=ring_path, data=rings_data, meta=rings_add_kwargs
            )
            print(
                f"Successfully loaded rings from ROXAS RingTraces for {file_path}"
            )

        except FileNotFoundError as e:
            print(f"Error loading rings from {file_path}: {e}")
            print("Continue without loading rings for this file.")
            return

    def run(self):
        """
        Process all image files from the project directory.

        This is the main entry point for the worker thread.
        """
        # Find all image files in the project directory
        all_files = []

        # Gather all files with supported image extensions
        for ext in self.image_file_extensions:
            all_files.extend(
                glob.glob(
                    str(Path(self.project_directory) / "**" / f"*{ext}"),
                    recursive=True,
                )
            )
            all_files.extend(
                glob.glob(
                    str(
                        Path(self.project_directory) / "**" / f"*{ext.upper()}"
                    ),
                    recursive=True,
                )
            )

        # Filter based on selected files if provided
        if self.selected_files and len(self.selected_files) > 0:
            # Create a set of absolute paths for fast lookup
            selected_paths = {Path(f).absolute() for f in self.selected_files}
            # Only include files that are in the selected paths
            filtered_files = [
                f for f in all_files if Path(f).absolute() in selected_paths
            ]
            all_files = filtered_files

        # Filter out already processed files if needed
        if not self.process_processed:
            filtered_files = []
            for file_path in all_files:
                basename = Path(file_path).name
                if self.scan_content_extension not in basename:
                    filtered_files.append(file_path)
            all_files = filtered_files

        # Sort files for consistent processing
        self.all_files = sorted(all_files)

        # Process files or finish if none found
        total = len(self.all_files)
        self.current_file_index = 0

        if total > 0:
            self._process_next_file()
        else:
            self.finished.emit()

    def _process_next_file(self):
        """
        Process the next file in the queue.

        This function handles the main processing logic for each file.
        """
        # Check if we should stop or if we've processed all files
        if self.should_stop or self.current_file_index >= len(self.all_files):
            # Processing complete or stopped
            if not self.should_stop:
                self.progress.emit(len(self.all_files), len(self.all_files))
            self.finished.emit()
            return

        # Get current file path
        file_path = self.all_files[self.current_file_index]

        # Update progress indication
        self.progress.emit(self.current_file_index, len(self.all_files))

        # Extract path components
        dir_path = Path(file_path).parent
        file_name = Path(file_path).name
        base_name = Path(file_name).stem
        file_ext = Path(file_name).suffix

        # Create Path object for advanced path manipulation
        file_path_obj = Path(file_path)

        # Get the parent directory and pure stem (removing all extensions)
        parent_dir = file_path_obj.parent
        stem_name = file_path_obj.stem
        # Remove all suffixes to get the pure stem name if we are processing scan files again

        if stem_name.endswith(self.scan_content_extension):
            stem_name = Path(stem_name).stem

        # Create absolute stem path
        sample_stem_abs = (parent_dir / stem_name).resolve()

        # Store as relative to the project root if possible
        project_root = Path(self.project_directory).resolve()
        try:
            sample_stem_rel = sample_stem_abs.relative_to(project_root)
            sample_stem_path = (
                sample_stem_rel.as_posix()
            )  # store portable separators
        except ValueError:
            # If file isn't under project root, store as POSIX absolute
            sample_stem_path = sample_stem_abs.as_posix()

        # Check if base_name already has the scan extension and remove it to avoid duplication
        original_has_scan_ext = False
        if self.scan_content_extension in base_name:
            # This is an already processed file, extract the clean base name
            original_has_scan_ext = True
            clean_base_name = base_name.replace(
                self.scan_content_extension, ""
            )
            new_image_path = file_path  # Keep the original path
            print(f"Reprocessing already processed file: {file_path}")
            print(f"Clean base name: {clean_base_name}")
        else:
            # This is a new file, add the scan extension
            clean_base_name = base_name
            new_image_path = (
                dir_path
                / f"{clean_base_name}{self.scan_content_extension}{file_ext}"
            )
            # Rename or copy file if needed
            if file_path != str(new_image_path):
                try:
                    # Extract metadata before modifying the file
                    img_metadata = self._extract_image_metadata(file_path)

                    # Always avoid duplicates: rename if possible, else copy+delete
                    moved_path = self._safe_rename_or_copy_delete(
                        Path(file_path), Path(new_image_path)
                    )
                    print(f"Renamed file: {file_path} -> {moved_path}")

                    file_path = str(moved_path)
                except OSError as e:
                    print(f"Error processing file {file_path}: {e}")
                    self.current_file_index += 1
                    self._process_next_file()
                    return

        # Define metadata path - always use the clean base name without scan extension
        metadata_path = (
            dir_path / f"{clean_base_name}{self.metadata_file_extension}"
        )

        # Extract image metadata if we haven't already
        if "img_metadata" not in locals():
            img_metadata = self._extract_image_metadata(file_path)

        # Add sample_stem_path to the image metadata
        img_metadata["sample_stem_path"] = sample_stem_path

        # Cache metadata for use in set_metadata
        self._current_img_metadata = img_metadata

        # If we have default metadata and apply_to_all is true, use it
        if self.apply_to_all and self.default_metadata:
            # Use the cached metadata directly - no need to modify it
            # Just make a copy to ensure we don't modify the original
            metadata = self.default_metadata.copy()

            # Only update the sample name to match this file
            metadata["sample_name"] = clean_base_name

            # Add sample_stem_path to this file's metadata
            metadata["sample_stem_path"] = sample_stem_path

            # Add image metadata
            self._add_image_metadata_to_file_metadata(metadata, img_metadata)

            # Save metadata file
            self._save_metadata(metadata, metadata_path)

            # Load data from old roxas file formats if needed
            if self.default_loading_params.get("load_cells_from_roxas", False):
                self.load_cells_from_roxas_scl(file_path, metadata)

            if self.default_loading_params.get("load_rings_from_roxas", False):
                self.load_rings_from_roxas_ringtraces(file_path, metadata)

            # Move to next file
            self.current_file_index += 1
            self._process_next_file()
        else:
            # Request metadata from user via dialog - pass the clean base name
            self.metadata_request.emit(clean_base_name)
            # Processing will continue when metadata is provided via set_metadata

    def set_metadata(
        self,
        metadata: Dict,
        apply_to_all: bool = False,
        loading_params: Optional[Dict] = None,
    ):
        """
        Set metadata for current file and continue processing.

        Args:
            metadata: User-provided metadata dictionary
            apply_to_all: Whether to apply this metadata to all remaining files
        """
        # Get current file info
        file_path = self.all_files[self.current_file_index]
        dir_path = Path(file_path).parent
        file_name = Path(file_path).name
        base_name = Path(file_name).stem

        # Extract clean base name (without scan extension) for the metadata file path
        if self.scan_content_extension in base_name:
            clean_base_name = base_name.replace(
                self.scan_content_extension, ""
            )
        else:
            clean_base_name = base_name

        # Create metadata path using clean base name
        metadata_path = (
            dir_path / f"{clean_base_name}{self.metadata_file_extension}"
        )

        # Use the cached image metadata
        img_metadata = self._current_img_metadata

        # Add image metadata to the file metadata
        self._add_image_metadata_to_file_metadata(metadata, img_metadata)

        # Save the metadata file
        self._save_metadata(metadata, metadata_path)

        # Update apply_to_all flag and store default metadata if needed
        self.apply_to_all = apply_to_all
        if apply_to_all:
            # Store the complete metadata for future files
            self.default_metadata = metadata.copy()
            self.default_loading_params = loading_params.copy()

        # Load data from old roxas file formats if needed
        if loading_params.get("load_cells_from_roxas", False):
            self.load_cells_from_roxas_scl(file_path, metadata)

        if loading_params.get("load_rings_from_roxas", False):
            self.load_rings_from_roxas_ringtraces(file_path, metadata)

        # Clean up the temporary metadata cache
        self._current_img_metadata = None

        # Move to next file
        self.current_file_index += 1
        self._process_next_file()

    def _add_image_metadata_to_file_metadata(
        self, metadata: Dict, img_metadata: Dict
    ):
        """
        Add image metadata to the file metadata.

        Args:
            metadata: File metadata dictionary to update
            img_metadata: Image metadata to add
        """
        if img_metadata:
            # Add image metadata fields without overwriting existing metadata
            # This preserves the sample_ fields from the dialog
            for key, value in img_metadata.items():
                if key not in metadata:
                    metadata[key] = value

    def _extract_image_metadata(self, image_path: str) -> Dict:
        """
        Extract metadata from an image file.

        Args:
            image_path: Path to the image file

        Returns:
            Dict: Image metadata
        """
        try:
            with Image.open(image_path) as img:
                # Store scan image information for metadata
                img_metadata = {
                    "scan_format": img.format,
                    "scan_size": [img.width, img.height],
                    "scan_mode": img.mode,
                }

                # Extract and preserve EXIF data if available
                if hasattr(img, "_getexif") and img._getexif() is not None:
                    exif_dict = {}
                    for tag_id, value in img._getexif().items():
                        tag_name = ExifTags.TAGS.get(tag_id, tag_id)
                        # Convert bytes to string or skip if not serializable
                        if isinstance(value, bytes):
                            try:
                                # Try to decode bytes as UTF-8
                                exif_dict[tag_name] = value.decode(
                                    "utf-8", errors="replace"
                                )
                            except (UnicodeDecodeError, AttributeError):
                                # If decoding fails, convert to hex string
                                exif_dict[tag_name] = f"0x{value.hex()}"
                        elif isinstance(
                            value, (str, int, float, bool, list, tuple, dict)
                        ):
                            exif_dict[tag_name] = value
                        else:
                            # Skip non-serializable types
                            exif_dict[tag_name] = str(value)

                    img_metadata["scan_exif"] = exif_dict
                else:
                    img_metadata["scan_exif"] = None

                # Extract other image info (excluding binary data)
                scan_info = {}
                for key, value in img.info.items():
                    if (
                        key != "exif"
                        and key != "icc_profile"
                        and isinstance(
                            value, (str, int, float, bool, tuple, list)
                        )
                    ):
                        scan_info[key] = value

                img_metadata["scan_info"] = scan_info

                return img_metadata

        except (OSError, ValueError, Image.UnidentifiedImageError) as e:
            print(f"Error extracting metadata from {image_path}: {e}")
            return {}  # Return empty dict on error

    def _save_metadata(self, metadata: Dict, metadata_path: str):
        """
        Save metadata to a JSON file.

        Args:
            metadata: Metadata dictionary to save
            metadata_path: Path to save the JSON file
        """
        try:
            # Ensure all data is JSON serializable
            sanitized_metadata = self._sanitize_for_json(metadata)

            with open(metadata_path, "w") as f:
                json.dump(sanitized_metadata, f, indent=4)
        except (OSError, TypeError) as e:
            print(f"Error saving metadata to {metadata_path}: {e}")

    def _sanitize_for_json(self, obj):
        """
        Recursively convert an object to a JSON-serializable format.

        Args:
            obj: Object to sanitize

        Returns:
            JSON-serializable version of the object
        """
        if isinstance(obj, dict):
            return {k: self._sanitize_for_json(v) for k, v in obj.items()}
        elif isinstance(obj, (list, tuple)):
            return [self._sanitize_for_json(item) for item in obj]
        elif isinstance(obj, bytes):
            try:
                return obj.decode("utf-8", errors="replace")
            except UnicodeDecodeError:
                return f"0x{obj.hex()}"
        elif isinstance(obj, (str, int, float, bool, type(None))):
            return obj
        else:
            # Convert other types to string
            return str(obj)

    def stop(self):
        """Stop the processing."""
        self.should_stop = True
